/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-04-11 13:26:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>My JSP 'menu.jsp' starting page</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/css/base.css\" type=\"text/css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/css/menu.css\" type=\"text/css\" />\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t    div {\r\n");
      out.write("\t\t\tpadding:0px;\r\n");
      out.write("\t\t\tmargin:0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t scrollbar-base-color:#C27E73;\r\n");
      out.write("\t\t scrollbar-arrow-color:#FFFFFF;\r\n");
      out.write("\t\t scrollbar-shadow-color:#D2A097;\r\n");
      out.write("\t\t padding:0px;\r\n");
      out.write("\t\t margin:auto;\r\n");
      out.write("\t\t text-align:center;\r\n");
      out.write("\t\t background-color:#FF8033;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdl.bitem {\r\n");
      out.write("\t\t\twidth:148px;\r\n");
      out.write("\t\t\tmargin:0px 0px 5px 4px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdl.bitem dt {\r\n");
      out.write("\t\t  background:url(");
      out.print(path );
      out.write("/img/menubg.gif);\r\n");
      out.write("\t\t  height:26px;\r\n");
      out.write("\t\t  line-height:26px;\r\n");
      out.write("\t\t  text-align:center;\r\n");
      out.write("\t\t  cursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdl.bitem dd {\r\n");
      out.write("\t\t  padding:3px 3px 3px 3px;\r\n");
      out.write("\t\t  background-color:#fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.fllct\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twidth:90px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.flrct\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpadding-top:3px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdiv.items\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tline-height:22px;\r\n");
      out.write("\t\t\tbackground:url(");
      out.print(path );
      out.write("/img/arr4.gif) no-repeat 10px 9px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tspan.items\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpadding:10px 0px 10px 22px;\r\n");
      out.write("\t\t\tbackground:url(");
      out.print(path );
      out.write("/img/arr4.gif) no-repeat 10px 12px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tul {\r\n");
      out.write("\t\t  padding-top:3px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tli {\r\n");
      out.write("\t\t  height:22px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.sitemu li {\r\n");
      out.write("\t\t\tpadding:0px 0px 0px 22px;\r\n");
      out.write("\t\t\tline-height:24px;\r\n");
      out.write("\t\t\tbackground:url(");
      out.print(path );
      out.write("/img/arr4.gif) no-repeat 10px 9px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script language='javascript'>var curopenItem = '1';</script>\r\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/menu.js\"></script>\r\n");
      out.write("\t<base target=\"main\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body target=\"main\">\r\n");
      out.write("\t<table width='99%' height=\"100%\" border='0' cellspacing='0' cellpadding='0'>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td style='padding-left:3px;padding-top:8px' valign=\"top\">\r\n");
      out.write("\t\t  <!-- 1 -->\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items1_1\")'><b>修改个人密码</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items1_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t            <li><a href='");
      out.print(path );
      out.write("/admin/index/userinfo.jsp' target='main'>修改个人密码</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items5_1\")'><b>商品信息管理</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items5_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t             <li><a href='");
      out.print(path );
      out.write("/catelogMana.action' target='main'>类别信息管理</a> </li>\r\n");
      out.write("\t             <li><a href='");
      out.print(path );
      out.write("/goodsManaNoTejia.action' target='main'>商品信息管理</a> </li>\r\n");
      out.write("                  <li><a href='");
      out.print(path );
      out.write("/goodsKucun.action' target='main'>库存信息管理</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items6_1\")'><b>订单信息管理</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items6_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t             <li><a href='");
      out.print(path );
      out.write("/userMana.action' target='main'>会员信息管理</a> </li>\r\n");
      out.write("\t             <li><a href='");
      out.print(path );
      out.write("/orderMana.action' target='main'>订单信息管理</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items6_1\")'><b>财务信息管理</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items6_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t            \r\n");
      out.write("\t             <li><a href='");
      out.print(path );
      out.write("/caiwuMana.action' target='main'>财务信息统计</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items3_1\")'><b>客服公告管理</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items3_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t            <li><a href='");
      out.print(path );
      out.write("/liuyanMana.action' target='main'>客服回复管理</a> </li>\r\n");
      out.write("\t            <li><a href='");
      out.print(path );
      out.write("/gonggaoMana.action' target='main'>公告信息管理</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items3_1\")'><b>品牌推荐管理</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items3_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t            <li><a href='");
      out.print(path );
      out.write("/keywordEdit.action' target='main'>首页品牌推荐管理</a> </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t      <dl class='bitem'>\r\n");
      out.write("\t        <dt onClick='showHide(\"items99_1\")'><b>安全退出系统</b></dt>\r\n");
      out.write("\t        <dd style='display:block' class='sitem' id='items99_1'>\r\n");
      out.write("\t          <ul class='sitemu'>\r\n");
      out.write("\t            <li><a href='#' onclick='javascript:window.parent.location=\"");
      out.print(path );
      out.write("/login.jsp\"'>安全退出系统</a></li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </dd>\r\n");
      out.write("\t      </dl>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
