/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-04-11 13:26:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link href=\"");
      out.print(path );
      out.write("/css/base.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script language='javascript'>\r\n");
      out.write("\t\tvar preFrameW = '206,*';\r\n");
      out.write("\t\tvar FrameHide = 0;\r\n");
      out.write("\t\tvar curStyle = 1;\r\n");
      out.write("\t\tvar totalItem = 9;\r\n");
      out.write("\t\tfunction ChangeMenu(way){\r\n");
      out.write("\t\t\tvar addwidth = 10;\r\n");
      out.write("\t\t\tvar fcol = top.document.all.btFrame.cols;\r\n");
      out.write("\t\t\tif(way==1) addwidth = 10;\r\n");
      out.write("\t\t\telse if(way==-1) addwidth = -10;\r\n");
      out.write("\t\t\telse if(way==0){\r\n");
      out.write("\t\t\t\tif(FrameHide == 0){\r\n");
      out.write("\t\t\t\t\tpreFrameW = top.document.all.btFrame.cols;\r\n");
      out.write("\t\t\t\t\ttop.document.all.btFrame.cols = '0,*';\r\n");
      out.write("\t\t\t\t\tFrameHide = 1;\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\ttop.document.all.btFrame.cols = preFrameW;\r\n");
      out.write("\t\t\t\t\tFrameHide = 0;\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfcols = fcol.split(',');\r\n");
      out.write("\t\t\tfcols[0] = parseInt(fcols[0]) + addwidth;\r\n");
      out.write("\t\t\ttop.document.all.btFrame.cols = fcols[0]+',*';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction logout()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t   if(confirm(\"确定要退出本系统吗??\"))\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t\t   window.parent.location=\"");
      out.print(path );
      out.write("/login.jsp\";\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t}\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body bgColor='#ffffff' style=\"margin: 0;padding: 0\">\r\n");
      out.write("\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"");
      out.print(path );
      out.write("/img/topbg.gif\">\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td width='70%' height=\"60\" style=\"font-size:26px; font-weight: bold;\">&nbsp;&nbsp;网上商城系统</td>\r\n");
      out.write("\t    <td width='30%' align=\"right\">\r\n");
      out.write("\t    \t<table width=\"400\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t\t      <td align=\"right\" height=\"26\" style=\"padding-right:10px;line-height:26px;font-size:17px\">\r\n");
      out.write("\t\t\t        \t<font style=\"font-size:16px; font-weight: bold;\">\r\n");
      out.write("\t\t\t        \t    您好：系统管理员&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t        \t</font>\r\n");
      out.write("\t\t\t        \t<!--  [<a href=\"\" target=\"_blank\">网站主页</a>]-->\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t        \t[<a href=\"#\" onclick=\"logout()\">注销退出</a>]\r\n");
      out.write("\t\t\t\t\t\t[<a href=\"javascript:ChangeMenu(0);\">显示主框架</a>]\r\n");
      out.write("\t\t\t      </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t        </table>\r\n");
      out.write("\t    </td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
