/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-04-11 13:26:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>login.jsp</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/style.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".style2 {\r\n");
      out.write("\tcolor: #990000\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input2 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tborder: 3px double #A8D0EE;\r\n");
      out.write("\tcolor: #344898;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit1 {\r\n");
      out.write("\tborder: 3px double #416C9C;\r\n");
      out.write("\theight: 22px;\r\n");
      out.write("\twidth: 45px;\r\n");
      out.write("\tbackground-color: #F2F2F2;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tpadding-top: 1px;\r\n");
      out.write("\tbackground-image: url(bt.gif);\r\n");
      out.write("\tcursor: hand;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".STYLE12 {\r\n");
      out.write("\tfont-family: Georgia, \"Times New Roman\", Times, serif\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".STYLE13 {\r\n");
      out.write("\tcolor: #316BD6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".STYLE15 {\r\n");
      out.write("\tcolor: #fdsere;\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript'\r\n");
      out.write("\tsrc='");
      out.print(path);
      out.write("/dwr/interface/loginService.js'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(path);
      out.write("/dwr/engine.js'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(path);
      out.write("/dwr/util.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write(" function check1()\r\n");
      out.write(" {                                                                                         \r\n");
      out.write("     if(document.ThisForm.userName.value==\"\")\r\n");
      out.write("\t {\r\n");
      out.write("\t \talert(\"请输入用户名\");\r\n");
      out.write("\t\tdocument.ThisForm.userName.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(document.ThisForm.userPw.value==\"\")\r\n");
      out.write("\t {\r\n");
      out.write("\t \talert(\"请输入密码\");\r\n");
      out.write("\t\tdocument.ThisForm.userPw.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t }\r\n");
      out.write("\t document.getElementById(\"indicator\").style.display=\"block\";\r\n");
      out.write("\t loginService.login(document.ThisForm.userName.value,document.ThisForm.userPw.value,0,callback);\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" function callback(data)\r\n");
      out.write(" {\r\n");
      out.write("    document.getElementById(\"indicator\").style.display=\"none\";\r\n");
      out.write("    if(data==\"no\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"用户名或密码错误\");\r\n");
      out.write("    }\r\n");
      out.write("    if(data==\"yes\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"通过验证,系统登录成功\");\r\n");
      out.write("        window.location.href=\"");
      out.print(path);
      out.write("/loginSuccess.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction keyLogin() {\r\n");
      out.write("\t\tif (event.keyCode == 13) //回车键的键值为13\r\n");
      out.write("\t\t\tdocument.getElementByIdx_x(check1()).click(); //调用登录按钮的登录事件\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onkeydown=\"keyLogin();\">\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table width=\"650px\" height=\"423\" border=\"0\" align=\"center\"\r\n");
      out.write("\t\tcellpadding=\"0\" cellspacing=\"0\" background=\"");
      out.print(path);
      out.write("/img/dfff.jpg\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\"\r\n");
      out.write("\t\t\t\t\tstyle=\"FONT-WEIGHT: bold; FONT-SIZE: 33pt;\">&nbsp;&nbsp;&nbsp;&nbsp;</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"650px\">\r\n");
      out.write("\t\t\t\t<form name=\"ThisForm\" method=\"POST\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<table width=\"360\" height=\"198\" border=\"0\" align=\"right\"\r\n");
      out.write("\t\t\t\t\t\tcellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"10\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100\" height=\"22\" align=\"right\" valign=\"bottom\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"STYLE15\">用户名：</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260\" valign=\"bottom\"><input name=\"userName\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"input2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOver=\"this.style.background='#F0DAF3';\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOut=\"this.style.background='#FFFFFF'\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"10\" colspan=\"2\" valign=\"bottom\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"22\" valign=\"top\" class=\"STYLE15\" align=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalign=\"bottom\">密&nbsp;&nbsp;&nbsp;&nbsp;码：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260\" valign=\"bottom\"><input name=\"userPw\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" size=\"21\" class=\"input2\" align=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOver=\"this.style.background='#F0DAF3';\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOut=\"this.style.background='#FFFFFF'\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"10\" colspan=\"2\" valign=\"bottom\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" valign=\"top\" align=\"center\">&nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp; &nbsp; <input name=\"button\" type=\"button\" class=\"submit1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"登录\" onClick=\"check1()\"> &nbsp; <input\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"Submit2\" type=\"reset\" class=\"submit1\" value=\"重置\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"indicator\" src=\"");
      out.print(path);
      out.write("/img/loading.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"display: none\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
